# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-29 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doggo',
            fields=[
                ('dog_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('job_desc', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(height_field=200, upload_to='images/', width_field=200)),
            ],
        ),
    ]
