# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-29 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doggo',
            name='profile_picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
